name: build

on:
  push:
    branches:
      - master
  workflow_run:
    workflows: ["regenerate"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22.19.0

      - run: pnpm install

      - run: pnpm lint

      - run: pnpm build

      - run: pnpm build:cron

      - run: pnpm build:public

      - uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          port: ${{ secrets.REMOTE_PORT }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist/analyse.js"
          target: ${{ secrets.REMOTE_TARGET_CRON }}
          strip_components: 1

      - uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          port: ${{ secrets.REMOTE_PORT }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "public/*,!public/static/*"
          target: ${{ secrets.REMOTE_TARGET_PUBLIC }}
          strip_components: 1
