name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: corepack enable

      - run: pnpm install

      - run: pnpm lint

      - run: pnpm build

      - run: pnpm build:cron

      - run: pnpm build:public

      - uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_HOST }}
          port: ${{ secrets.REMOTE_PORT }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist/analyse.js"
          target: ${{ secrets.REMOTE_TARGET_CRON }}
          strip_components: 1

      - uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_HOST }}
          port: ${{ secrets.REMOTE_PORT }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "public/index.html,public/main.js,public/main.css"
          target: ${{ secrets.REMOTE_TARGET_PUBLIC }}
          strip_components: 1
