name: regenerate

on:
  workflow_dispatch:

jobs:
  regenerate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v6
        with:
          node-version: 24.11.0

      - run: pnpm install

      - run: pnpm build:static

      - uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Action
          author_email: github-actions[bot]@users.noreply.github.com
          message: |
            chore: update static data
          add: public/static/* src/data/generated/*

      - uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          port: ${{ secrets.REMOTE_PORT }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "public/static/*"
          target: ${{ secrets.REMOTE_TARGET_PUBLIC }}
          strip_components: 1
